spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sumeru?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root@123
  redis:
    database: 0
    password: "fit2cloud"
